services:

  db:

    image: postgres

    ports:
      - 5432:5432

    user: postgres

    environment:
      - POSTGRES_PASSWORD=password

    # Seed database with initial tables and data
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
